#ifndef ITEMSTATS_H
#define ITEMSTATS_H

enum class ItemStats {
    Agility = 0,
    Intellect,
    Spirit,
    Stamina,
    Strength,
    Armor,
    Defense,
    DodgeChance,
    ParryChance,
    ResistanceArcane,
    ResistanceFire,
    ResistanceFrost,
    ResistanceHoly,
    ResistanceNature,
    ResistanceShadow,
    ResistanceAll,
    SkillAxe,
    SkillDagger,
    SkillMace,
    SkillSword,
    SkillBow,
    SkillCrossbow,
    SkillGun,
    HitChance,
    CritChance,
    AttackSpeedPercent,
    AttackPower,
    APVersusBeast,
    APVersusDemon,
    APVersusDragonkin,
    APVersusElemental,
    APVersusGiant,
    APVersusHumanoid,
    APVersusMechanical,
    APVersusUndead,
    MeleeAttackPower,
    RangedAttackPower,
    ManaPer5,
    SpellDamage,
    SpellCrit,
    SpellHit,
};

#endif // ITEMSTATS_H
