#include "Shadow.h"

#include "Talent.h"
#include "TalentStatIncrease.h"
#include "Priest.h"
#include "PriestSpells.h"

    Shadow::Shadow(Priest* priest) :
    TalentTree("Shadow", "Assets/priest/priest_curses.jpg"), priest(priest), spells(static_cast<PriestSpells*>(priest->get_spells())) {
    talent_names_to_locations = {
            {"Spirit Tap", "1ML"},
            {"Blackout", "1MR"},
            {"Shadow Affinity", "2LL"},
            {"Improved Shadow Word: Pain", "2ML"},
            {"Shadow Focus", "2MR"},
            {"Improved Psychic Scream", "3LL"},
            {"Improved Mind Blast", "3ML"},
            {"Mind Flay", "3MR"},
            {"Improved Fade", "4ML"},
            {"Shadow Reach", "4MR"},
            {"Shadow Weaving", "4RR"},
            {"Silence", "5LL"},
            {"Vampiric Embrace", "5ML"},
            {"Improved Vampiric Embrace", "5MR"},
            {"Darkness", "6MR"},
            {"Shadow Form", "7ML"}
        };

    QMap<QString, Talent*> tier1 {
        {"1ML", new Talent(priest, this, "Spirit Tap", "1ML", "Assets/spell/", 5,
                           "Gives you a %1% chance to gain a %1% bonus to your Spirit after killing a target that yields experience.  For the duration, your Mana will regenerate at a 50% rate while casting.  Lasts 15 sec.",
                           QVector<QPair<unsigned, unsigned>> {{20, 20}})},
        {"1MR", new Talent(priest, this, "Blackout", "1MR", "Assets/spell/Spell_shadow_shadowwordpain.png", 5,
                           "Gives your Shadow damage spells a %1% chance to stun the target for 3 sec.",
                           QVector<QPair<double, double>> {{2, 2}})}
    };
    add_talents(tier1);

    QMap<QString, Talent*> tier2 {
        {"2LL", new Talent(priest, this, "Shadow Affinity", "2LL", "Assets/spell/", 3,
                           "Reduces the threat generated by your Shadow spells by %1%.",
                           QVector<QPair<unsigned, unsigned>> {{8, 8}})},
        {"2ML", new Talent(priest, this, "Improved Shadow Word: Pain", "2ML", "Assets/spell/", 2,
                           "Increases the duration of your Shadow Word: Pain spell by %1 sec.",
                           QVector<QPair<unsigned, unsigned>> {{50, 50}})},
        {"2ML", new Talent(priest, this, "Shadow Focus", "2MR", "Assets/spell/", 5,
                           "Reduces your target's chance to resist your Shadow spells by %1%.",
                           QVector<QPair<unsigned, unsigned>> {{2, 2}})}
    };
    add_talents(tier2);

    QMap<QString, Talent*> tier3 {
        {"3LL", new Talent(priest, this, "Improved Psychic Scream", "3LL", "Assets/spell/", 2,
                           "Reduces the cooldown of your Psychic Scream spell by %1% sec.",
                           QVector<QPair<unsigned, unsigned>> {{2, 2}})},
        {"3ML", new Talent(priest, this, "Improved Mind Blast", "3ML", "Assets/spell/", 5,
                           "Reduces the cooldown of your Mind Blast spell by %1% sec.",
                           QVector<QPair<double, double>> {{0.5, 0.5}})},
        {"3MR", new Talent(priest, this, "Mind Flay", "3MR", "Assets/spell/", 1,
                           "Assault the target's mind with Shadow energy, causing 75 Shadow damage over 3 sec and slowing their movement speed by 50%.",
                           QVector<QPair<unsigned, unsigned>> {})}
    };
    add_talents(tier3);

    QMap<QString, Talent*> tier4 {
        {"4ML", new Talent(priest, this, "Improved Fade", "4ML", "Assets/spell/", 2,
                           "Decreases the cooldown of your Fade ability by %1% sec.",
                           QVector<QPair<unsigned, unsigned>> {{3, 3}})},
        {"4MR", new Talent(priest, this, "Shadow Reach", "4MR", "Assets/spell/", 3,
                            "Increases the range of your Shadow damage spells by %1%.",
                            QVector<QPair<unsigned, unsigned>> {{6, 6}})},
        {"4RR", new Talent(priest, this, "Shadow Weaving", "4RR", "Assets/spell/", 5,
                            "Your Shadow damage spells have a %1% chance to cause your target to be vulnerable to Shadow damage.  This vulnerability increases the Shadow damage dealt to your target by 3% and lasts 15 sec.  Stacks up to 5 times.",
                            QVector<QPair<unsigned, unsigned>> {{20, 20}})}
    };
    add_talents(tier4);

    QMap<QString, Talent*> tier5 {
        {"5LL", new Talent(priest, this, "Silence", "5LL", "Assets/spell/", 1,
                           "Silences the target, preventing them from casting spells for 5 sec.",
                           QVector<QPair<unsigned, unsigned>> {})},
        {"5ML", new Talent(priest, this, "Vampiric Embrace", "5ML", "Assets/spell/", 1,
                           "Afflicts your target with Shadow energy that causes all party members to be healed for 20% of any Shadow spell damage you deal for 1 min.",
                           QVector<QPair<unsigned, unsigned>> {})},
        {"5MR", new Talent(priest, this, "Improved Vampiric Embrace", "5MR", "Assets/spell/", 2,
                           "Increases the percentage healed by Vampiric Embrace by an additional %1%.",
                           QVector<QPair<unsigned, unsigned>> {{5, 5}})}
    };
    add_talents(tier5);

    QMap<QString, Talent*> tier6 {
        {"6MR", new Talent(priest, this, "Darkness", "6MR", "Assets/spell/", 5,
                           "Increases your Shadow spell damage by 2%.",
                           QVector<QPair<unsigned, unsigned>> {{5, 5}})}
    };
    add_talents(tier6);

    QMap<QString, Talent*> tier7 {
        {"5MR", new Talent(priest, this, "Shadow Form", "7ML", "Assets/spell/", 1,
                           "Assume a Shadowform, increasing your Shadow damage by 15% and reducing Physical damage done to you by 15%.  However, you may not cast Holy spells while in this form.",
                           QVector<QPair<unsigned, unsigned>> {})},
    };
    add_talents(tier7);

    talents["3LL"]->talent->set_bottom_child(talents["5LL"]->talent);
    talents["5LL"]->talent->set_parent(talents["3LL"]->talent);

    talents["5ML"]->talent->set_bottom_child(talents["7ML"]->talent);
    talents["7ML"]->talent->set_parent(talents["5ML"]->talent);

    talents["5ML"]->talent->set_right_child(talents["5MR"]->talent);
    talents["5MR"]->talent->set_parent(talents["5ML"]->talent);
}
